### ISSUE TITLE
"For Open Source Projects" Page

### ISSUE THREAD

**Issue by monarchwadia** [MintbeanHackathons/MintbeanPlatform#10]
We should encourage Open Source projects to come join us. This page will support the Mintbean team in reaching out to this target audience and so bring more value + visibility to the community.

Content to be provided by Monarch Wadia.

**Comment by alandeivson** [comment]
Hi, monarch!
I'm willing to help the MintbeanPlatform.
Can you send or post a prototype of this page?
Do we have a designer?

**Comment by monarchwadia** [comment]
Hi @alandeivson we don't use a designer. Content will be text only, maybe some lightweight images, plus a video.

**Comment by monarchwadia** [comment]
Hi @alandeivson we've decided to revisit this as a team, will reopen this if there is still need. Thanks for taking a look. Can you pick up another ticket?
