### ISSUE TITLE
Create a backend README.md

### ISSUE THREAD

**Issue by monarchwadia** [MintbeanHackathons/MintbeanPlatform#13]
We need instructions on getting started
EDIT: This is for creating getting-started instructions for the backend project, only

**Comment by Sumedh-Patkar** [comment]
I wasn't suggesting a README exactly.

We can't put everything in the README. 
Let's say tomorrow the project becomes huge, then readme will become too clumsy.

Can we have a _'how to contribute'_ documentation on a platform like [https://readthedocs.org/](https://readthedocs.org/) ?

The documentation will contain everything from setting up the development environment to visual guidelines

Have a look at this example - 
https://docs.aiohttp.org/en/stable/contributing.html

Your thoughts?

**Comment by AzaniaBG** [comment]
I can work on this. I just need to know if there is any information that I need to reference and where I can find it.

**Comment by monarchwadia** [comment]
@Sumedh-Patkar those are excellent points. For a project of this size, maintaining documentation on the Github itself is a lightweight way to get started.

Eventually, once we need it, we absolutely should get hosted docs -- for now though, i think we can run with what Github gives us.

**Comment by monarchwadia** [comment]
@AzaniaBG you can get started by creating a README for how to get the backend started.

**Comment by AzaniaBG** [comment]
@carloshdelreal will be handling this
