### ISSUE TITLE
Migrate to Bootstrap

### ISSUE THREAD

**Issue by monarchwadia** [MintbeanHackathons/MintbeanPlatform#15]
Use https://github.com/bootstrap-vue/bootstrap-vue to move over to Bootstrap

Styles will change for all pages, probably, so we need someone who can keep styling relatively clean.

**Comment by derekjj** [comment]
I tend to use this on all my projects so I will take this one.

**Comment by derekjj** [comment]
https://github.com/MintbeanHackathons/MintbeanPlatform/pull/25

**Comment by derekjj** [comment]
monarchwadia commented

> Hey man. Closing this one for now. I think it's a bit early to move to bootstrap, we can get by with just plain CSS. It'll keep things looking fresh and organically written.
