### ISSUE TITLE
Display version number of the project

### ISSUE THREAD

**Issue by monarchwadia** [MintbeanHackathons/MintbeanPlatform#19]
For backend, add an API endpoint that displays the version number.

For frontend, add a little text div on the bottom-right that displays the version number, in a light-gray.
For frontend, please also a little text div on the bottom-right that displays the BACKEND'S version number, as received from API, in a light-gray.

Please make sure the verison number is being pulled from `package.json`. For example, 
```
require('../package.json').version;
```

**Comment by leanjunio** [comment]
Hey Monarch, I'd like to try this ticket out.
