### ISSUE TITLE
Needs a backend README.md

### ISSUE THREAD

**Issue by monarchwadia** [MintbeanHackathons/MintbeanPlatform#2]

**Comment by monarchwadia** [comment]
I'll take this on

**Comment by monarchwadia** [comment]
Changing this to 'Needs a Backend README.md'

**Comment by carloshdelreal** [comment]
Now I will tackle the backend Readme

**Comment by carloshdelreal** [comment]
I don't fully understand this issue tracking workflow but this is very similar to the issue 12 Create a backend README.md

**Comment by carloshdelreal** [comment]
I added this pr https://github.com/MintbeanHackathons/MintbeanPlatform/pull/29 to this issue

**Comment by monarchwadia** [comment]
#29

**Comment by monarchwadia** [comment]
Thanks @carloshdelreal !!
