### ISSUE TITLE
"For Educators" Page

### ISSUE THREAD

**Issue by monarchwadia** [MintbeanHackathons/MintbeanPlatform#3]
Create a page to explain the value of the Platform to educators. This page will support the Mintbean team in reaching out to this target audience and so bring more value + visibility to the community.

Navi Mann currently has content that can be put up on the platform.

**Comment by shohei-shibata** [comment]
Hey @monarchwadia I'd love to give this a shot! I am new to Vue and I'll be learning as I go. If you're willing to be patient 😄 please share with me the content.

**Comment by monarchwadia** [comment]
hi @shohei-shibata still waiting on my team to provide this. will be in touch :-)

**Comment by monarchwadia** [comment]
I've added you to the #mintbean-platform channel on Discord. 

There's a project kickoff meeting at 3pm on Friday -- no worries if you cannot make it, it's totally fine. :-)

**Comment by monarchwadia** [comment]
Hi Shohei,

Please find a copy of the content.

https://docs.google.com/document/d/1TjFLPYHkDnrGEXSlzpJ7qigsmsH68hFohHgz6FqXYuU/edit?usp=sharing

**Comment by shohei-shibata** [comment]
Hi Monarch,

Thank you! Are you available any time after 5pm today (EDT) to chat?

**Comment by monarchwadia** [comment]
hi @shohei-shibata i am available all weekend. Are you available?

**Comment by shohei-shibata** [comment]
@monarchwadia I am available, mostly any time this weekend.
