### ISSUE TITLE
shift(alignment difference)

### ISSUE THREAD

**Issue by derekjj** [MintbeanHackathons/MintbeanPlatform#34]
Constancy between pages
http://localhost:8080/
http://localhost:8080/scores
vs
http://localhost:8080/guidebook
http://localhost:8080/for-educators

for example

**Comment by monarchwadia** [comment]
Seems to be an issue with the scrollbar causing the page to reposition
Maybe this is the solution: https://stackoverflow.com/questions/1417934/how-to-prevent-scrollbar-from-repositioning-web-page

**Comment by shohei-shibata** [comment]
I can take on this issue tonight
