### ISSUE TITLE
"For Employers" page

### ISSUE THREAD

**Issue by monarchwadia** [MintbeanHackathons/MintbeanPlatform#7]
We need a page which will tell Employers how we can help them. This page will support the Mintbean team in reaching out to this target audience and so bring more value + visibility to the community.

Monarch Wadia or Joseph Karim to provide content for this section.

**Comment by jennifer-tang** [comment]
Test 123

**Comment by mintbean-volunteers** [comment]
test

**Comment by ajinkya002** [comment]
@monarchwadia:  I am interested for this page.

**Comment by monarchwadia** [comment]
Hi @ajinkya002 , 

We're actually revisiting this now, will be closing this request. Can you possibly pick up another ticket?
