### ISSUE TITLE
"For Developers"

### ISSUE THREAD

**Issue by monarchwadia** [MintbeanHackathons/MintbeanPlatform#9]
We need to create a page that explains the value of the hackathons to developers. This page will support the Mintbean team in reaching out to this target audience and so bring more value + visibility to the community.

We need separate content that appeals to:

1. Junior Developers
1. Intermediate/Senior Developers
1. Hiring Managers

**Comment by Peter-White** [comment]
So like a homepage for Mintbean?

**Comment by monarchwadia** [comment]
Hi @Peter-White this will be a separate page, but will have one of the most prominent links on the homepage dedicated to it.

**Comment by monarchwadia** [comment]
I've added you to the #mintbean-platform channel on Discord. 

There's a project kickoff meeting at 3pm on Friday -- no worries if you cannot make it, it's totally fine. :-)

**Comment by monarchwadia** [comment]
Closing this for now as we revisit the strategy for this page
